// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20251023210055_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Iznajmljivanja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojDana")
                        .HasColumnType("bigint");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Iznajmljivanja");
                });

            modelBuilder.Entity("WebTemplate.Models.Kola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojSedista")
                        .HasColumnType("bigint");

                    b.Property<long>("CenaPoDanu")
                        .HasColumnType("bigint");

                    b.Property<bool>("DaLiJeIznajmljen")
                        .HasColumnType("bit");

                    b.Property<long>("Godiste")
                        .HasColumnType("bigint");

                    b.Property<int?>("IznajmljivanjeFK")
                        .HasColumnType("int");

                    b.Property<long>("Kilometraza")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IznajmljivanjeFK")
                        .IsUnique()
                        .HasFilter("[IznajmljivanjeFK] IS NOT NULL");

                    b.HasIndex("ModelID");

                    b.ToTable("Kola");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojDozvole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeIPrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("WebTemplate.Models.Modeli", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Modeli");
                });

            modelBuilder.Entity("WebTemplate.Models.Iznajmljivanja", b =>
                {
                    b.HasOne("WebTemplate.Models.Korisnik", "Korisnik")
                        .WithMany("Iznajmljivanjas")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("WebTemplate.Models.Kola", b =>
                {
                    b.HasOne("WebTemplate.Models.Iznajmljivanja", "Iznajmljivanje")
                        .WithOne("Kola")
                        .HasForeignKey("WebTemplate.Models.Kola", "IznajmljivanjeFK");

                    b.HasOne("WebTemplate.Models.Modeli", "Model")
                        .WithMany("Kolas")
                        .HasForeignKey("ModelID");

                    b.Navigation("Iznajmljivanje");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("WebTemplate.Models.Iznajmljivanja", b =>
                {
                    b.Navigation("Kola")
                        .IsRequired();
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Navigation("Iznajmljivanjas");
                });

            modelBuilder.Entity("WebTemplate.Models.Modeli", b =>
                {
                    b.Navigation("Kolas");
                });
#pragma warning restore 612, 618
        }
    }
}
