// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20251023234623_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BazicnaCena")
                        .HasColumnType("int");

                    b.Property<int>("BrojRedova")
                        .HasColumnType("int");

                    b.Property<int>("BrojSale")
                        .HasColumnType("int");

                    b.Property<string>("ImeFilma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremeReprodukcije")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("WebTemplate.Models.Sediste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SalaaID")
                        .HasColumnType("int");

                    b.Property<bool?>("Zauzeto")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("SalaaID");

                    b.ToTable("Sediste");
                });

            modelBuilder.Entity("WebTemplate.Models.Sediste", b =>
                {
                    b.HasOne("WebTemplate.Models.Sala", "Salaa")
                        .WithMany("Sedista")
                        .HasForeignKey("SalaaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salaa");
                });

            modelBuilder.Entity("WebTemplate.Models.Sala", b =>
                {
                    b.Navigation("Sedista");
                });
#pragma warning restore 612, 618
        }
    }
}
