// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20251027100048_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Film", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("KategorijaFilmaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocene")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KategorijaFilmaID");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("WebTemplate.Models.Kategorija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProdukcijskaKucaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProdukcijskaKucaID");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("WebTemplate.Models.Kuca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kuca");
                });

            modelBuilder.Entity("WebTemplate.Models.Film", b =>
                {
                    b.HasOne("WebTemplate.Models.Kategorija", "KategorijaFilma")
                        .WithMany("Filmovi")
                        .HasForeignKey("KategorijaFilmaID");

                    b.Navigation("KategorijaFilma");
                });

            modelBuilder.Entity("WebTemplate.Models.Kategorija", b =>
                {
                    b.HasOne("WebTemplate.Models.Kuca", "ProdukcijskaKuca")
                        .WithMany("Kategorije")
                        .HasForeignKey("ProdukcijskaKucaID");

                    b.Navigation("ProdukcijskaKuca");
                });

            modelBuilder.Entity("WebTemplate.Models.Kategorija", b =>
                {
                    b.Navigation("Filmovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Kuca", b =>
                {
                    b.Navigation("Kategorije");
                });
#pragma warning restore 612, 618
        }
    }
}
