// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("Mesec")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Placen")
                        .HasColumnType("bit");

                    b.Property<int?>("StannID")
                        .HasColumnType("int");

                    b.Property<long?>("Struja")
                        .HasColumnType("bigint");

                    b.Property<long?>("Usluge")
                        .HasColumnType("bigint");

                    b.Property<long>("Voda")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("StannID");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("WebTemplate.Models.Stan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojClanova")
                        .HasColumnType("bigint");

                    b.Property<string>("ImeVlasnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Stan");
                });

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.HasOne("WebTemplate.Models.Stan", "Stann")
                        .WithMany("Racuni")
                        .HasForeignKey("StannID");

                    b.Navigation("Stann");
                });

            modelBuilder.Entity("WebTemplate.Models.Stan", b =>
                {
                    b.Navigation("Racuni");
                });
#pragma warning restore 612, 618
        }
    }
}
